In [54]:
import pandas as pd
#read_csv()
df = pd.read_csv("all_bip.csv")
new_df = df.drop(columns=['RowNum', 'pa_of_inning', 'pitch_of_pa', 'batter_side', 'pitcher_throws', 'outs','balls','strikes','tagged_pitch_type'])
new_df.groupby(['play_result']).mean().sort_values("exit_speed", ascending = False)

                exit_speed      angle  direction    distance    bearing
play_result
HomeRun         103.564584  28.213486  -2.028699  400.118244  -1.747968
Triple           97.586745  20.120352   9.951198  303.221003  13.664727
Double           97.326549  16.626925  -3.817449  264.312806  -3.909124
Single           89.751320   6.264910  -2.406049  143.365378  -1.765964
Out              85.252010  13.953233   0.007042  150.991733   0.458863
Error            84.726466  -6.287160  -6.955740   58.893099  -5.490504
Undefined        83.093043  16.716667  -5.996377  182.933333  -6.318551
FieldersChoice   82.568008 -12.783992  -7.218497   28.561605  -6.123943
Sacrifice        70.643226   3.295348   1.996409  195.952374   2.272519